### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by adamjgrant** [gavindinubilo/jam-api#10]
`post_connection_check': hostname "www.jamapi.xyz" does not match the server certificate (OpenSSL::SSL::SSLError)

If I'm reading this right, there is an issue with the SSL certificate for jamapi.xyz?

This was after running just the demo code for ruby provided on the main page

```
require 'httparty'
require 'json'
response = HTTParty.post("https://www.jamapi.xyz/",
{ 
  :body => [ { "url" => "http://www.radcircle.com", "json_data" => "{'title': 'title'}"} ].to_json,
  :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'}
})  
puts JSON.parse(response)
```

**Comment by gavindinubilo** [comment]
oh, shoot, should be "http://www.jamapi.xyz", I've also updated the ruby example to be a little simpler.

**Comment by adamjgrant** [comment]
Cheers.

**Comment by adamjgrant** [comment]
Erm, did you mean to put

    HTTParty.post("http://localhost:5000/"

?

**Comment by adamjgrant** [comment]
https://github.com/gavindinubilo/jam-api/pull/11

**Comment by gavindinubilo** [comment]
Nope, didn't mean to put that, quickly copy pasted from a test file. Thanks for the pull request, I've merged it in.
