### ISSUE TITLE
Is this applicable client side ?

### ISSUE THREAD

**Issue by Swizz** [gavindinubilo/jam-api#14]
Hi there !

This idea looks pretty cool for micro scraping services.
But today, as I read, it works server side. 

It could be more usefull to create a client side version of Jam to make possible to create many and many github pages who scrap the web.

For exemple, I am looking for a way to turn my city transportation service website into an api without hosting cost (thanks to github pages).

Cheers,

**Comment by gavindinubilo** [comment]
Yep this for sure works client side, you'd just use a ajax. I reckon I should add an example to the list. Here's an example using https://github.com/github/fetch
```
fetch('http://www.jamapi.xyz', {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    url: 'http://www.radcircle.com',
    json_data: '{"title": "title"}'})
}).then(function(response) {
  return response.json();
}).then(function(json) {
  document.body.innerHTML = json;
});  
```

**Comment by gavindinubilo** [comment]
I've added an example to the readme for browser side javascript.

**Comment by Swizz** [comment]
Thanks you a lot !
