### ISSUE TITLE
http://www.jamapi.xyz/ with https

### ISSUE THREAD

**Issue by Quezler** [gavindinubilo/jam-api#16]
It would be nice if http://www.jamapi.xyz/ could also be served with https.

My personal suggestion (and how i did it on my own server):

- Have apache
- Get free https://letsencrypt.org/ certificate
- Setup apache proxypass to the http instance of http://www.jamapi.xyz/ on localhost
- Done 👍 

(I'll be here if you have questions/need help doing it 🆘)

**Comment by gavindinubilo** [comment]
I'll take a look this weekend

**Comment by Quezler** [comment]
Any luck?

**Comment by gavindinubilo** [comment]
Not quite, the site is currently hosted on heroku, and I'm pretty sure they charge big bucks to provide ssl (that's where they make most of their money). Gonna look into maybe some (better) free hosting over the weekend, if you have any suggestions, I'd love to hear them.

**Comment by gavindinubilo** [comment]
I don't think it requires a ton to run, would AWS be a good idea? I'm currently paying $7/month on the hobby plan (whatever the hell that means) to keep it up 100% of the time. Anything less than $7/mo would be perfect.

**Comment by Quezler** [comment]
In that case i would suggest one of these 3 : https://www.ovh.co.uk/vps/vps-ssd.xml

**Comment by gavindinubilo** [comment]
ok, sweet, I'll check it out. Just for data reference, here's a screenshot of memory usage over the past 24 hours. Not sure if helpful or not

![screen shot 2016-09-02 at 10 45 42 am](https://cloud.githubusercontent.com/assets/2745145/18212912/97c2bccc-70fa-11e6-8792-f668e9c48e7f.png)

**Comment by Quezler** [comment]
Seems like VPS 1 on the link i sent will be more than capable of running it :D

**Comment by gavindinubilo** [comment]
Awesome, thanks for the help @Quezler!!

**Comment by Quezler** [comment]
do you have experience with setting up vps's?

**Comment by gavindinubilo** [comment]
not a ton, I have a little experience setting up servers on digital ocean, and lots for heroku

**Comment by Quezler** [comment]
well if you run into any troubles, let me know, i have years of experience

**Comment by gavindinubilo** [comment]
awesome will do

**Comment by Quezler** [comment]
Any progress? 💭

**Comment by Quezler** [comment]
Any news at all?

**Comment by gavindinubilo** [comment]
I'm working on it now, heroku made it free to have ssl when you have a non-free dyno, sorry for the delay, I've been under the weather for a few weeks.

**Comment by gavindinubilo** [comment]
@Quezler jamapi.xyz now has SSL support, I moved the server to digital ocean, and used letsencrypt to obtain a cert, this will probably turn out to be the cheapest as well. Gonna close this issue out now.
