### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Tomino2112** [gavindinubilo/jam-api#3]
Hi,

What license are you releasing this under?

Thank you

**Comment by Plloi** [comment]
Package.json says ISC

**Comment by gavindinubilo** [comment]
Totally spaced with adding a license, what's a suggested license do you think?

**Comment by wookiecooking** [comment]
I suggest MIT or GPL.  I would love to use this project but no license holds me back.

**Comment by gavindinubilo** [comment]
@Tomino2112 I added in the GPL license.
