### ISSUE TITLE
Support for more attributes?

### ISSUE THREAD

**Issue by kasbah** [gavindinubilo/jam-api#5]
Would it be possible to select by other tag attributes? I am currently looking at parsing sites that have a lot of unique `itemprop` attributes like: `<td itemprop="description">IC MCU 8BIT 32KB FLASH 44TQFP</td>` from [this site](http://www.digikey.co.uk/product-detail/en/atmel/ATMEGA32U4-AU/ATMEGA32U4-AU-ND/1914602) but hardly any ids or classes. I think these are ASP sites.

**Comment by omgmog** [comment]
Behind the scenes, this Jam API is using [Cheerio](https://github.com/cheeriojs/cheerio).

So you can target a specific element quite easily using [attribute selectors](https://www.w3.org/TR/selectors/#attribute-selectors), or even [structural pseudo element selectors](https://www.w3.org/TR/selectors/#structural-pseudos)

e.g.

To select any `<td itemprop="description">`:

```css
td[itemprop=description]
```


To get the second `td` in a table, for every `tr` after the third `tr`:

```css
tr:nth-child(n+3) td:nth-child(2)
```

Or to get the first occurrence of an element:

```css
td:first-of-type
```

**Comment by kasbah** [comment]
Oh, yeah.. neat!

More concretely, you can: 
```
 curl -d url=http://www.digikey.co.uk/product-detail/en/atmel/ATMEGA32U4-AU/ATMEGA32U4-AU-ND/1914602 -d json_data='{"description":"td[itemprop=description]"}' http://www.jamapi.xyz/ 
```
to get
```json
{
    "description": "\n                                                IC MCU 8BIT 32KB FLASH 44TQFP\n                                            "
}
```

I guess the bug is for this to be better documented.
