### ISSUE TITLE
http://www.jamapi.xyz/ -> "Application Error"

### ISSUE THREAD

**Issue by frdmn** [gavindinubilo/jam-api#7]
![bildschirmfoto 2016-04-29 um 10 00 21](https://cloud.githubusercontent.com/assets/944459/14910834/39b4bf34-0df1-11e6-885b-1118975616aa.png)

Just noticed this and thought I'll let you know.

**Comment by gavindinubilo** [comment]
Thanks for the heads up, the site's currently on a heroku dyno, and it requires to be asleep for 6 hours minimum on the free version. I'm going to look into transferring it to it's own DO box today so it's not forced to go down. 

I'll close this issue once I get it transferred.

**Comment by gavindinubilo** [comment]
I upgraded the Heroku Dyno, so there should be no more of these errors. It will take a tad longer to load sometimes, because of how Heroku does things with shutting servers down, but for the most part I think that's alright.

Gonna go ahead and close this issue.

**Comment by frdmn** [comment]
👍
